### ISSUE TITLE
Add log level

### ISSUE THREAD

**Issue by obriankevin11** [GioF71/minidlna-docker#14]
Hi,
Could you add log level parameter to the list?
Thank you!

**Comment by GioF71** [comment]
Sure, will do

**Comment by GioF71** [comment]
A new variable named `MINIDLNA_LOG_LEVEL` is available now.

**Comment by obriankevin11** [comment]
That was fast! Thank you!

**Comment by GioF71** [comment]
Consider starring the repo if you like my work. Thank you!
