### ISSUE TITLE
container restarts everytime

### ISSUE THREAD

**Issue by matthiasklabe** [GioF71/minidlna-docker#19]
Hi,

If I use your image and deploy the stack in portainer I get this error message in the log files of the container

"minidlna.c:1028: fatal: Failed to open log file '/log/minidlna.log': Permission denied"

could you please check and advise ?

THX
Matthias

**Comment by matthiasklabe** [comment]
I'm using Debian bookworm at an AMD64 Server with Docker 25.0.0

**Comment by GioF71** [comment]
Hello, looks like a permission issue, can you post your compose file?

**Comment by matthiasklabe** [comment]
---
version: "3"

services:
  minidlna-desktop:
    image: giof71/minidlna
    container_name: minidlna
    network_mode: host
    user: "1000:1000"
    environment:
      - MINIDLNA_ROOT_CONTAINER=M
      - MINIDLNA_DIR_A_1=/music/library1
      - MINIDLNA_DIR_A_2=/music/library2
      - MINIDLNA_DIR_A_3=/music/library3
      - MINIDLNA_ENABLE_INOTIFY=YES
      - MINIDLNA_FRIENDLY_NAME=minidlna
      - MINIDLNA_FORCE_SORT_CRITERIA=+upnp:class,-dc:date,+upnp:album,+upnp:originalTrackNumber,+dc:title
    volumes:
      - /mnt/disk1/library:/music/library1
      - /mnt/disk2/library:/music/library2
      - /mnt/disk3/library:/music/library3
      - ./config/log:/log
      - ./config/db:/db
    restart: unless-stopped

**Comment by GioF71** [comment]
Ok, can you please post the output of 

`id`

Assuming it will be 1000:1000, I believe you should do:

```
docker-compose down
sudo chown -R 1000:1000 ./config
docker-compose up -d
```
Let me know if this helps

**Comment by matthiasklabe** [comment]
THX for fast reply.
I started this stack with portainer and I have some other stacks running as well.

docker-compose.yml will be used several times for the other stacks as well.

docker-compose down is not working in ssh console.

Sorry I'm a "newbee" in this topic.

**Comment by GioF71** [comment]
Which error do you get when running docker-compose down?
I think you might have not installed docker, compose. You can install it using

`sudo apt-get install docker-compose`

Ok if you are using Portainer, these "./config/..." path won't work and/or are not the best idea. You need absolute paths.
I would drop the line that says

user: "1000:1000"

and would instead add the two variables:

PUID=1000
PGID=1000

I would create two volumes, named e.g. minidlna_db and minidlna_log and I would map those to /db and /log respectively, using the GUI.
But in order to make things simple, you can try first without any mounted directory for /db and /tmp

Let me know if this helps

**Comment by GioF71** [comment]
Sorry also add variable:

`USER_MODE=Y`

so that you can eventually deny it easily

**Comment by matthiasklabe** [comment]
Hi,
volume is working, but container is restarting... you can see console and portainer log in the background.

![image](https://github.com/GioF71/minidlna-docker/assets/154374589/4c4d0856-1bfe-4163-8a86-016bd2a56ab4)

**Comment by GioF71** [comment]
I don't see the final part of the log... and I cannot open the image, can you post the text?
The part you highlighted is ok, the script is changing the permissions on the volumes (it can do that because it is not run in docker user mode)

**Comment by matthiasklabe** [comment]
This is the log which I copied out of portainer:

Current user id is [0]
t=A
Processing media_dir for ENV_NAME=[/music/library1]
t=P
Processing media_dir for ENV_NAME=[]
t=V
Processing media_dir for ENV_NAME=[]
t=A
Processing media_dir for ENV_NAME=[/music/library2]
t=P
Processing media_dir for ENV_NAME=[]
t=V
Processing media_dir for ENV_NAME=[]
t=A
Processing media_dir for ENV_NAME=[/music/library3]
t=P
Processing media_dir for ENV_NAME=[]
t=V
Processing media_dir for ENV_NAME=[]
t=A
Processing media_dir for ENV_NAME=[]
t=P
Processing media_dir for ENV_NAME=[]
t=V
Processing media_dir for ENV_NAME=[]
t=A
Processing media_dir for ENV_NAME=[]
t=P
Processing media_dir for ENV_NAME=[]
t=V
Processing media_dir for ENV_NAME=[]
group minidlna-user already exists.
user minidlna-user already exists.
Setting user permissions on /log ...
Setting user permissions on /db ...
User permissions set.
# MINIDLNA CONFIG
media_dir=A,/music/library1
media_dir=A,/music/library2
media_dir=A,/music/library3
db_dir=/db

log_dir=/log
root_container=M

0
friendly_name=minidlna
inotify=yes
album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg
album_art_names=AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg
album_art_names=Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg
force_sort_criteria=+upnp:class,-dc:date,+upnp:album,+upnp:originalTrackNumber,+dc:title
CMD_LINE=/usr/sbin/minidlnad -S -f /tmp/minidlna.conf -P /tmp/minidlnad.pid
USER_MODE=[Y]
USER_MODE with uid[1000] gid[1000]
---------------------------------------------------------------------------------------------------------------------
and then it restarts.
In other cases the ports causes issues, but the host has no used ports

**Comment by GioF71** [comment]
do the paths:

/mnt/disk1/library
/mnt/disk2/library
/mnt/disk3/library

actually exist? they look the same I provided as an examples. You need to tune those values to your actual paths

**Comment by GioF71** [comment]
Which directory/directories do you want to serve with minidlna?

**Comment by matthiasklabe** [comment]
minidlna-log from Volumê

![image](https://github.com/GioF71/minidlna-docker/assets/154374589/58db41f2-4375-49bf-aad7-c4c63083dd23)

**Comment by matthiasklabe** [comment]
you could be right to serve special dirctories, but I thought this is generic setup

**Comment by GioF71** [comment]
> you could be right to serve special dirctories, but I thought this is generic setup

yes but I cannot know which will be the path(s) you want to share... only you know that, which names you gave to your media directories, etc. You need to provide that/those paths

Maybe I need to clarify this in the readme file.

**Comment by GioF71** [comment]
Those paths have been create now in your filesystem although they are probably empty, you can clean those by:

sudo rmdir /mnt/disk1/library /mnt/disk2/library /mnt/disk3/library

**Comment by matthiasklabe** [comment]
![image](https://github.com/GioF71/minidlna-docker/assets/154374589/95737aa9-1a12-466e-a9f2-0fbc2b27ec2a)

**Comment by GioF71** [comment]
those look like errors when network_mode is not host. Are you still using the compose file or manipulating the container using portainer?

**Comment by matthiasklabe** [comment]
I'm using compose file which is still in my private gitlab. In portainer I'm using "pull and re-deploy"

**Comment by GioF71** [comment]
do you see other minidlna containers active in portainer?

**Comment by GioF71** [comment]
Let's get these path correct first then we see if the errors persist.
Can you tell me the full path of the media files you want to share?

**Comment by matthiasklabe** [comment]
There is nothing to share right now, but I will put something into /var/lib/docker/volumes/music1/_data....this is clear so far.
It should only work for the little kid. Around 20 songs ;-) Later I want to use it by myself a bit more.

To answer your question, there is no minidlna container running

![image](https://github.com/GioF71/minidlna-docker/assets/154374589/e5178746-77a3-4b78-86a8-0cd7d0bfedd2)

**Comment by matthiasklabe** [comment]
![image](https://github.com/GioF71/minidlna-docker/assets/154374589/17c3e43a-e7ed-4650-9234-df36c70f6bce)

**Comment by GioF71** [comment]
try removing that `restart: unless-stopped`, and re-create the container

**Comment by matthiasklabe** [comment]
it starts and it stopped after some time

**Comment by GioF71** [comment]
ok so can you post the last log?

**Comment by GioF71** [comment]
is any container possibly using port 8200?

**Comment by matthiasklabe** [comment]
I don't know where you from, but I don't want you to spend your "night" for my problem. I'm from Germany and it is around 7 p.m.

![image](https://github.com/GioF71/minidlna-docker/assets/154374589/28c7d906-7495-418c-bd61-258aedba8011)

**Comment by matthiasklabe** [comment]
maybe the port need to be add into the docker-compose.yml?

**Comment by GioF71** [comment]
No worries, we're on the same TZ, I'm from Italy
I don't see 8200 in that list, am I wrong? Plot tickens

**Comment by matthiasklabe** [comment]
yes there is no 3200, maybe it need to add in YML

**Comment by GioF71** [comment]
Seeing the log I noticed this:

No such file or directory

Have you corrected the mount points for the libraries?

**Comment by matthiasklabe** [comment]
If you mean /run/minssdpd  - NO.
I dont know why this need to be there... I started from scratch with headless DEBIAN bookworm. Then installed some additionals like "net-tools" and "mc". Then Installes Docker.io 25.0.0 and went forward with partainer and adding stacks out of my private gitlab.

![image](https://github.com/GioF71/minidlna-docker/assets/154374589/35dbe0b0-6d2f-4ac5-a947-6839f21d2e39)

**Comment by matthiasklabe** [comment]
I found out, right away, that this is needed in the host to provide DLNA from Host

**Comment by matthiasklabe** [comment]
I istalled it at my docker host an will let you know

**Comment by GioF71** [comment]
No I mean the paths for your files. Let's try starting simple. I assume you want to share music but if not, replace "A" with "V".
Simpler docker-compose file:


```
---
version: "3"

services:
  minidlna-desktop:
  image: giof71/minidlna
  container_name: minidlna
  network_mode: host
  environment:
   - USER_MODE=Y
   - PUID=1000
   - PGID=1000
   - MINIDLNA_ROOT_CONTAINER=M
   - MINIDLNA_DIR_A_1=/music/library1
   - MINIDLNA_ENABLE_INOTIFY=YES
   - MINIDLNA_FRIENDLY_NAME=minidlna
   - MINIDLNA_FORCE_SORT_CRITERIA=+upnp:class,-dc:date,+upnp:album,+upnp:originalTrackNumber,+dc:title
  volumes:
   - /path/to/music:/music/library1
```

**Comment by GioF71** [comment]
> I istalled it at my docker host an will let you know

So did you solve it?

**Comment by matthiasklabe** [comment]
unfortunately not.
I used "sudo apt get install minissdpd" an rebooted the system. Service is now running at the host and missing file is also there
![image](https://github.com/GioF71/minidlna-docker/assets/154374589/38509371-08be-4736-8e06-e316c003d75a)

![image](https://github.com/GioF71/minidlna-docker/assets/154374589/22658bc9-5d92-4ca8-b62c-8859895e8df5)

**Comment by matthiasklabe** [comment]
after a second restart, minissdpd does not come up proper and .sock file is also disapeared. An mentioned I'm expecting this "minissdpd" in the container. Anyways - take your time to investigate - no stress ;-)

**Comment by GioF71** [comment]
I never experienced this... I am currently clueless.
Can you try [this](https://hub.docker.com/r/vladgh/minidlna/) other minidlna docker container and see if this one works?

**Comment by matthiasklabe** [comment]
![image](https://github.com/GioF71/minidlna-docker/assets/154374589/8c0757f9-cc70-4906-8f4e-18ca8a90bed9)

**Comment by matthiasklabe** [comment]
to be honest I tried it before as well, with same result

**Comment by GioF71** [comment]
uhm ok, that's encouraging at least :-)

**Comment by matthiasklabe** [comment]
Could be that it is related to bookworm 64 bit, but I don't want to downgrade.

**Comment by GioF71** [comment]
I can't exclude it... the server I am running it on is bullseye, but with that I am not encouraging to downgrade of course (I wouldn't)

**Comment by matthiasklabe** [comment]
IF you find the solution and send me you paypal, I will spend some money ;-)

**Comment by GioF71** [comment]
Thank you, not it won't be necessary, but thank you anyway

**Comment by GioF71** [comment]
Hello, if you install minidlna on the host machine, does it work properly? Thank you

**Comment by matthiasklabe** [comment]
I crashed yesterday my whole system, but it is again fresh up and running. No minissdpd installed yet, all ports same status as yesterday. It was not working with installed minissdpd in the old setup.

**Comment by GioF71** [comment]
I would try the minidlna from the packages and see if the problem happens there as well... if so, this would need to be fixed before trying to make the docker version work, IMO

**Comment by GioF71** [comment]
Looking here:

https://sourceforge.net/p/minidlna/discussion/879957/thread/0e0ea75c/

Maybe we should check if udp port 1900 is used with a

netstat -nlp | grep 1900

**Comment by GioF71** [comment]
also about daloradious, the repo for your docker image has been archived in 2022, there is an updated fork [here](https://github.com/hardreton/daloradius-docker), it might be somehow better than that now old image

**Comment by GioF71** [comment]
Also (and I stop spamming) I would try stopping the other docker containers, in order to exclude potential conflicts

**Comment by GioF71** [comment]
Awesome... the log in minidlna could have been a bit clearer and this would have been easier. But minidlna is I believe in life support currently. It works but it won't be updated significantly :-)

**Comment by matthiasklabe** [comment]
It is just to support a little girl with here music ... maybe I will use is later by myself as well :-)

**Comment by GioF71** [comment]
Closing this... feel free to open another issue if there are other problems or other information are needed.
Cheers
