### ISSUE TITLE
Increase the " Inotify max_user_watches"

### ISSUE THREAD

**Issue by MarcAndrea** [GioF71/minidlna-docker#21]
Hello, i have this error : 
monitor.c:222: warn: WARNING: Inotify max_user_watches [54938] is low or close to the number of used watches [6] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.

How we can changed the "max_user_watches" ? 

Thanks in advance
Regards

**Comment by GioF71** [comment]
Hello, did this work? I tried myself and it worked for me. Thank you

**Comment by MarcAndrea** [comment]
Hello, i will try this day. I come back to give you a feed back :) Thanks for your answer.

**Comment by MarcAndrea** [comment]
Hello, i have did the workaround and he doesn't work (See the picture).
![minidlna](https://github.com/GioF71/minidlna-docker/assets/70076329/4f1cfbc8-62d8-4396-920d-c01afecb5fd1)
 
Here is some additional information:

1) Error in the log file:
monitor.c:222: warn: WARNING: Inotify max_user_watches [54938] is low or close to the number of used watches [529] and I do not have permission to increase this limit. Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.

2) I tried to change the value but the FS does not have write permissions:
root@46dc232cecd3:/app/bin# mount | grep /proc/sys
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)

**Comment by MarcAndrea** [comment]
Hello, well now it's good!
Thanks for your help.

I have another question because now the database is created but I didn't see the DLNA server on VLC. (For information on the server on which I have DLNA I have 2 active VPNs)
Can VPNs create network flow problems to detect the server? I have access to the port 8200 WEB site

**Comment by GioF71** [comment]
> Hello, well now it's good! Thanks for your help.
> 

Ok good to hear!

> I have another question because now the database is created but I didn't see the DLNA server on VLC. (For information on the server on which I have DLNA I have 2 active VPNs) Can VPNs create network flow problems to detect the server? I have access to the port 8200 WEB site

Usually DLNA libraries require to be in the same network in order to be used. So having access to the 8200 port is usually not enough to be able to access the libraries.
For these scenarios, usually it might be advisable to use other kind of media servers, like for example Jellyfin (video and audio), or Navidrome (audio), Lightweight Music Server (audio) etc which are web-based.

How did you create your VPN?

**Comment by MarcAndrea** [comment]
My PC's connection to the DLNA server remains within the LAN network. 
I have 1 VPN used to connect to the NAS to access movies via NFS and another VPN to access services such as AD, DNS, ansible, etc ...

If you want we can do a call, and i will show you my problem.

**Comment by MarcAndrea** [comment]
Hello, my timezone is UTC +1, i'm at work today we can do call at 20 hours ? 
Which platform ? Discord or other ?

**Comment by GioF71** [comment]
Same timezone :-)
That time is a bit too late for today, is there any chance for 18:00, (almost) any other day?
Discord is OK although I never used that for call, but yes, I have an account, so it's good to go I think.

**Comment by MarcAndrea** [comment]
Es tu francais ? 

 I finish my work at 18h30, i can Friday all the afternoon or this week. 
 
 Have a nice day

**Comment by GioF71** [comment]
I'm from Italy :-)
What about 18:00 this friday?

**Comment by MarcAndrea** [comment]
Hello, I have good news, it works now.

I deleted containers, images and docker. After reinstallation it works.
I think the container was set to "host" on my openvpn card.

Is it possible to force the container to use my eth0 card?
I think it's no longer necessary to make the call, then we can still do it so you can see if it could come back?

**Comment by GioF71** [comment]
Hello, I believe what you ask should be possible, although a change in the container image code is needed.
See [here](https://man.archlinux.org/man/extra/minidlna/minidlna.conf.5.en#network_interface), there is the option to select the network interfaces to serve.
In your case, supposing the NETWORK_INTERFACES variable is available (it will be soon), you would still need to use network_mode: host, but you will be able to restrict minidlna to only use a subset of network interfaces.

**Comment by MarcAndrea** [comment]
Hello, really really thank you! I will try this new version this evening after work.
I want to thank you again, I didn't expect you to make a feature and even less so quickly. You made my day happy! :D

For information in the case where you create a qbittorrent container with an option to put a VPN under openVPN, know that I will be the first to download it :smile:

Have a nice day.

**Comment by GioF71** [comment]
Hello, thank you for the kind words, please star the repo if you can, this is always encouraging

**Comment by MarcAndrea** [comment]
It's done, i have put a star on the repo ! :smiley:

**Comment by GioF71** [comment]
I assume it should be working. Closing this, feel free to open another one if needed. Thank you
