### ISSUE TITLE
Permission denied for log file

### ISSUE THREAD

**Issue by luvxinh** [GioF71/minidlna-docker#27]
I got this error in the log.
minidlna.c:1028: fatal: Failed to open log file '/log/minidlna.log': Permission denied.

And I think the container keeps restarting.

I've got the user 1000:1000 as per default.

**Comment by GioF71** [comment]
Hello, can you post your compose file?
If you are running with `- user: 1000:1000`, you must provide a writable mountpoint to `/log`.
That's something I should work on, and maybe write in /tmp/log if /log is not writable.

**Comment by luvxinh** [comment]
Sorry my bad. I thought I've assumed ownership of the folders, but turned out I did not.

It works now. Thank you

**Comment by GioF71** [comment]
Hello, thank you for reporting anyway. In other containers I maintain I already remediate automatically these kind of misconfigurations by redirecting to /tmp/somedir when the directory is not writable, which can happend when forcing user mode and not providing writable directories to the mountpoints. I will open an issue for that.

Please star the repo if you like the work, this is always encouraging.

Cheers
