### ISSUE TITLE
Library is recreated when the container is restarted - expected?

### ISSUE THREAD

**Issue by Andrewkha** [GioF71/minidlna-docker#32]
Hi!
I noticed that the media library is recreated from the scratch every time the container restarts. Is this an expected behavior?
I also noticed that /config/log and /config/db mounts are empty...

**Comment by Andrewkha** [comment]
Please ignore... I looked at closed issues and realized I had permissions issue and logs and db went to /tmp. Solved

**Comment by GioF71** [comment]
Thank you @Andrewkha for reporting the resolution. Please star the repo if you like the work.
Cheers
