### ISSUE TITLE
Option notify_interval won't be inherited

### ISSUE THREAD

**Issue by luckyfreddy** [GioF71/minidlna-docker#6]
Hello. Thanks for the great implementation of minidlna in docker(-compose). Unfortunately the environment-option
"      - MINIDLNA_NOTIFY_INTERVAL=20"
in the docker-compose.yml-file won't be implemented in the "/app/conf/minidlna.conf" in the container. The option will be ignored. Is there an hidden option to set for implementing it?

The option "notify_interval" set the time to broadcast and the value of 20 is the only way to getting recognized by my TV after powering on.

Great thanks for checking.

**Comment by GioF71** [comment]
Hello, there is simply no support in this project for that variable, it's not in the Dockerfile and also not in the documentation.
But it looks like it is a very good idea to add it, I will check how to set it correctly!

**Comment by GioF71** [comment]
Hello @luckyfreddy, please check the latest image and the updated README.md file.
Let me know if this work as expected.

**Comment by luckyfreddy** [comment]
Now tested and it worked. I really appreciate this. Thanks.

**Comment by GioF71** [comment]
Thank you. Consider starring the repo if this is not an issue for you. Cheers!

**Comment by luckyfreddy** [comment]
Sure. Hope I have done it right cause i'm new at github.

**Comment by GioF71** [comment]
Yes you did it right, thank you!
